const FOOD_IMG = {
  roll: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=160&h=160&fit=crop',
  baked: 'https://images.unsplash.com/photo-1611145349180-c897967ccc10?w=160&h=160&fit=crop',
  set: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=160&h=160&fit=crop',
  nigiri: 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=160&h=160&fit=crop',
  pizza: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=160&h=160&fit=crop',
  coke: 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=160&h=160&fit=crop',
  fanta: 'https://images.unsplash.com/photo-1624517452131-7951379b58fa?w=160&h=160&fit=crop',
  sprite: 'https://images.unsplash.com/photo-1625772452859-1c03d5bf1137?w=160&h=160&fit=crop',
  fries: 'https://images.unsplash.com/photo-1573080496216-bb080ab9b0ec?w=160&h=160&fit=crop',
  nugget: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=160&h=160&fit=crop',
  mozz: 'https://images.unsplash.com/photo-1531741397117-0a86d5a0c8f0?w=160&h=160&fit=crop',
  dragon: 'https://images.unsplash.com/photo-1583623025818-d180aef1fc0b?w=160&h=160&fit=crop',
  spicy: 'https://images.unsplash.com/photo-1617196034183-421ce9f0d1c8?w=160&h=160&fit=crop',
};

const CATEGORIES = [
  {id:'philadelphia', label:{TR:'PHILADELPHIA ROLLS',EN:'PHILADELPHIA ROLLS',DE:'PHILADELPHIA ROLLS',RU:'PHILADELPHIA ROLLS'}},
  {id:'california', label:{TR:'CALIFORNIA ROLLS',EN:'CALIFORNIA ROLLS',DE:'CALIFORNIA ROLLS',RU:'CALIFORNIA ROLLS'}},
  {id:'sets', label:{TR:'SETS',EN:'SETS',DE:'SETS',RU:'СЕТЫ'}},
  {id:'canada', label:{TR:'CANADA ROLLS',EN:'CANADA ROLLS',DE:'CANADA ROLLS',RU:'CANADA ROLLS'}},
  {id:'maki', label:{TR:'MAKI ROLLS',EN:'MAKI ROLLS',DE:'MAKI ROLLS',RU:'МАКИ ROLLS'}},
  {id:'hoso', label:{TR:'HOSO ROLLS',EN:'HOSO ROLLS',DE:'HOSO ROLLS',RU:'ХОСО ROLLS'}},
  {id:'pizza', label:{TR:'PIZZA',EN:'PIZZA',DE:'PIZZA',RU:'ПИЦЦА'}},
  {id:'bonito', label:{TR:'BONITO ROLLS',EN:'BONITO ROLLS',DE:'BONITO ROLLS',RU:'БОНИТО ROLLS'}},
  {id:'tempura', label:{TR:'TEMPURA ROLLS',EN:'TEMPURA ROLLS',DE:'TEMPURA ROLLS',RU:'ТЕМПУРА ROLLS'}},
  {id:'tempura-light', label:{TR:'TEMPURA LIGHT ROLLS',EN:'TEMPURA LIGHT ROLLS',DE:'TEMPURA LIGHT ROLLS',RU:'ТЕМПУРА ЛАЙТ'}},
  {id:'sensei', label:{TR:'SENSEI ROLLS',EN:'SENSEI ROLLS',DE:'SENSEI ROLLS',RU:'СЕНСЕЙ ROLLS'}},
  {id:'dragon', label:{TR:'DRAGON ROLLS',EN:'DRAGON ROLLS',DE:'DRAGON ROLLS',RU:'ДРАКОН ROLLS'}},
  {id:'geisha', label:{TR:'GEISHA ROLLS',EN:'GEISHA ROLLS',DE:'GEISHA ROLLS',RU:'ГЕЙША ROLLS'}},
  {id:'haiku', label:{TR:'HAIKU ROLLS',EN:'HAIKU ROLLS',DE:'HAIKU ROLLS',RU:'ХАЙКУ ROLLS'}},
  {id:'spicy', label:{TR:'SPICY ROLLS',EN:'SPICY ROLLS',DE:'SPICY ROLLS',RU:'ОСТРЫЕ ROLLS'}},
  {id:'hawai', label:{TR:'HAWAI ROLLS',EN:'HAWAI ROLLS',DE:'HAWAI ROLLS',RU:'ГАВАЙИ ROLLS'}},
  {id:'nigiri', label:{TR:'NIGIRI & YINYANG ROLLS',EN:'NIGIRI & YINYANG ROLLS',DE:'NIGIRI & YINYANG ROLLS',RU:'НИГИРИ & ИНЬ-ЯН'}},
  {id:'drinks', label:{TR:'DRINK',EN:'DRINK',DE:'GETRÄNKE',RU:'НАПИТКИ'}},
  {id:'fries', label:{TR:'FRIES',EN:'FRIES',DE:'SNACKS',RU:'ЗАКУСКИ'}},
];

const MENU_ITEMS = [
  {id:1,cat:'philadelphia',name:'PHILEDEPHIA LIGHT',desc:'nori, rice, salmon, cheese, cucumber',price:'₺350,00',img:FOOD_IMG.roll},
  {id:2,cat:'philadelphia',name:'PHILEDELPHIA LÜX OVEN',desc:'Nori, rice, salmon, cheese, love sauce',price:'₺480,00',img:FOOD_IMG.baked},
  {id:3,cat:'philadelphia',name:'PHILEDELPHIA LÜX',desc:'Nori, rice, salmon, cheese, 8 pieces',price:'₺410,00',img:FOOD_IMG.roll},
  {id:4,cat:'california',name:'CALIFORNIA LUX',desc:'nori, rice, caviar, cucumber, crab stick',price:'₺310,00',img:FOOD_IMG.roll},
  {id:5,cat:'california',name:'CALIFORNIA LÜX OVEN',desc:'nori, rice, caviar, cucumber, crab stick',price:'₺380,00',img:FOOD_IMG.baked},
  {id:6,cat:'california',name:'CALIFORNIA MUSSEL',desc:'nori, rice, caviar, cucumber, mussel',price:'₺310,00',img:FOOD_IMG.roll},
  {id:7,cat:'sets',name:'SET 1 (PHILADELPHIA FAMILY)',desc:'Philadelphia Luxury, Philadelphia rolls',price:'₺1.500,00',img:FOOD_IMG.set},
  {id:8,cat:'sets',name:'SET 2 (SPICY FAMILY)',desc:'Spicy Salmon, Spicy Mussels, Spicy rolls',price:'₺1.320,00',img:FOOD_IMG.set},
  {id:9,cat:'sets',name:'SET 3 (FRIED FAMILY)',desc:'Tempura Light Eel, Tempura Baked Salmon',price:'₺1.650,00',img:FOOD_IMG.set},
  {id:10,cat:'canada',name:'CANADA SALMON',desc:'Nori, rice, cheese, cucumber, terayaki sauce',price:'₺440,00',img:FOOD_IMG.roll},
  {id:11,cat:'canada',name:'CANADA CRAB',desc:'Nori, rice, cucumber, terayaki sauce, crab',price:'₺400,00',img:FOOD_IMG.roll},
  {id:12,cat:'canada',name:'CANADA SHATAKI',desc:'Nori, rice, cheese, cucumber, terayaki sauce',price:'₺400,00',img:FOOD_IMG.roll},
  {id:13,cat:'maki',name:'SALMON MAKI',desc:'nori, rice, cheese, salmon, 8 pieces',price:'₺310,00',img:FOOD_IMG.roll},
  {id:14,cat:'maki',name:'BAKED SALMON MAKI',desc:'nori, rice, cheese, baked salmon, 8 pieces',price:'₺280,00',img:FOOD_IMG.baked},
  {id:15,cat:'maki',name:'SHATAKI MAKI',desc:'Nori, rice, cheese, shiitake mushroom',price:'₺300,00',img:FOOD_IMG.roll},
  {id:16,cat:'hoso',name:'HOSO UNAGI',desc:'nori, rice, eel, 6 pieces',price:'₺270,00',img:FOOD_IMG.roll},
  {id:17,cat:'hoso',name:'HOSO CRAB',desc:'nori, rice, crab sticks, 6 pieces',price:'₺230,00',img:FOOD_IMG.roll},
  {id:18,cat:'hoso',name:'HOSO HOPPA',desc:'nori, rice, cucumber, 6 pieces',price:'₺150,00',img:FOOD_IMG.roll},
  {id:19,cat:'pizza',name:'BOLOGNESE PIZZA',desc:'mozzarella cheese, dip sauce, bolognese',price:'₺350,00',img:FOOD_IMG.pizza},
  {id:20,cat:'pizza',name:'SALMON PIZZA',desc:'mozzarella cheese, dip sauce, salmon',price:'₺370,00',img:FOOD_IMG.pizza},
  {id:21,cat:'pizza',name:'MIX PIZZA',desc:'mozzarella cheese, dip sauce, mushroom',price:'₺400,00',img:FOOD_IMG.pizza},
  {id:22,cat:'bonito',name:'BONITO BAKED SALMON',desc:'Nori, rice, cheese, sesame, baked salmon',price:'₺310,00',img:FOOD_IMG.baked},
  {id:23,cat:'bonito',name:'BONITO MUSSEL',desc:'Nori, rice, cheese, cucumber, sesame',price:'₺320,00',img:FOOD_IMG.roll},
  {id:24,cat:'bonito',name:'BONITO SHRIMP',desc:'Nori, rice, cheese, cucumber, sesame',price:'₺350,00',img:FOOD_IMG.roll},
  {id:25,cat:'tempura',name:'SALMON TEMPURA',desc:'Nori, rice, cheese, scallions, cheddar',price:'₺350,00',img:FOOD_IMG.baked},
  {id:26,cat:'tempura',name:'CRAB TEMPURA',desc:'Nori, rice, scallions, terayaki sauce',price:'₺310,00',img:FOOD_IMG.baked},
  {id:27,cat:'tempura',name:'BAKED SALMON TEMPURA',desc:'Nori, rice, cheese, scallions, terayaki',price:'₺310,00',img:FOOD_IMG.baked},
  {id:28,cat:'tempura-light',name:'TEMPURA LIGHT HOPPA',desc:'Nori, rice, cheese, cucumber, terayaki',price:'₺290,00',img:FOOD_IMG.roll},
  {id:29,cat:'tempura-light',name:'TEMPURA LIGHT CRAB',desc:'Nori, rice, cucumber, terayaki sauce',price:'₺310,00',img:FOOD_IMG.roll},
  {id:30,cat:'tempura-light',name:'TEMPURA LIGHT SALMON',desc:'Nori, rice, cheese, cucumber, terayaki',price:'₺340,00',img:FOOD_IMG.roll},
  {id:31,cat:'sensei',name:'SENSEI BAKED SALMON',desc:'Nori, rice, cheese, love sauce, unagi sauce',price:'₺310,00',img:FOOD_IMG.baked},
  {id:32,cat:'sensei',name:'SENSEI SHRIMP',desc:'Nori, rice, cheese, love sauce, unagi sauce',price:'₺310,00',img:FOOD_IMG.roll},
  {id:33,cat:'sensei',name:'SENSEI CRAB',desc:'Nori, rice, love sauce, unagi sauce, sesame',price:'₺300,00',img:FOOD_IMG.roll},
  {id:34,cat:'dragon',name:'DRAGON MIX 2',desc:'Nori, rice, caviar, cheese, shataki mushroom',price:'₺500,00',img:FOOD_IMG.dragon},
  {id:35,cat:'dragon',name:'DRAGON MIX 1',desc:'Nori, rice, caviar, cheese, shataki mushroom',price:'₺500,00',img:FOOD_IMG.dragon},
  {id:36,cat:'dragon',name:'DRAGON BAKED SALMON',desc:'Nori, rice, caviar, cheese, shataki mushroom',price:'₺350,00',img:FOOD_IMG.dragon},
  {id:37,cat:'geisha',name:'GEISHA BAKED SALMON',desc:'Nori, rice, avocado, cheese, caviar, baked salmon',price:'₺340,00',img:FOOD_IMG.baked},
  {id:38,cat:'geisha',name:'GEISHA MUSSEL',desc:'Nori, rice, avocado, cheese, caviar, mussel',price:'₺350,00',img:FOOD_IMG.roll},
  {id:39,cat:'geisha',name:'GEISHA CRAB',desc:'Nori, rice, avocado, caviar, crab stick',price:'₺350,00',img:FOOD_IMG.roll},
  {id:40,cat:'haiku',name:'HAIKU MUSSEL',desc:'Nori, rice, cucumber, cheese, sesame',price:'₺300,00',img:FOOD_IMG.roll},
  {id:41,cat:'haiku',name:'HAIKU CRAB',desc:'Nori, rice, cucumber, sesame, crab stick',price:'₺300,00',img:FOOD_IMG.roll},
  {id:42,cat:'haiku',name:'HAIKU UNAGI',desc:'Nori, rice, cucumber, cheese, sesame',price:'₺340,00',img:FOOD_IMG.roll},
  {id:43,cat:'spicy',name:'SPICY CRAB',desc:'nori, rice, green onion, poppy, crab stick',price:'₺320,00',img:FOOD_IMG.spicy},
  {id:44,cat:'spicy',name:'SPICY BAKED SALMON',desc:'nori, rice, cheese, green onion, poppy',price:'₺330,00',img:FOOD_IMG.spicy},
  {id:45,cat:'spicy',name:'SPICY SHRIMP',desc:'nori, rice, cheese, green onion, poppy',price:'₺350,00',img:FOOD_IMG.spicy},
  {id:46,cat:'hawai',name:'HAWAI SHRIMP',desc:'nori, rice, cucumber, cheese, green onion',price:'₺340,00',img:FOOD_IMG.roll},
  {id:47,cat:'hawai',name:'HAWAI SHATAKI',desc:'nori, rice, cucumber, cheese, green onion',price:'₺330,00',img:FOOD_IMG.roll},
  {id:48,cat:'hawai',name:'HAWAI BAKED SALMON',desc:'nori, rice, cucumber, cheese, green onion',price:'₺350,00',img:FOOD_IMG.baked},
  {id:49,cat:'nigiri',name:'Salmon Nigiri (1 pieces)',desc:'Fresh salmon nigiri',price:'₺110,00',img:FOOD_IMG.nigiri},
  {id:50,cat:'nigiri',name:'Unagi Nigiri (1 pieces)',desc:'Grilled eel nigiri',price:'₺110,00',img:FOOD_IMG.nigiri},
  {id:51,cat:'nigiri',name:'Yinyang Shrimp',desc:'Rice, nori, cucumber, shrimp, 6 pieces',price:'₺320,00',img:FOOD_IMG.roll},
  {id:52,cat:'drinks',name:'COCA COLA 330 ML',desc:'Normal / Zero',price:'₺70,00',img:FOOD_IMG.coke},
  {id:53,cat:'drinks',name:'FANTA 330 ML',desc:'Orange soda',price:'₺70,00',img:FOOD_IMG.fanta},
  {id:54,cat:'drinks',name:'SPRITE 330 ML',desc:'Lemon-lime soda',price:'₺70,00',img:FOOD_IMG.sprite},
  {id:55,cat:'fries',name:'Nugget',desc:'8 pieces',price:'₺300,00',img:FOOD_IMG.nugget},
  {id:56,cat:'fries',name:'Mozzarella Sticks',desc:'8 pieces',price:'₺400,00',img:FOOD_IMG.mozz},
  {id:57,cat:'fries',name:'Chips',desc:'Crispy potato chips',price:'₺250,00',img:FOOD_IMG.fries},
];

const GOOGLE_REVIEWS = [
  {name:'Ahmet Y.',rating:5,text:{TR:'Harika sushi! Philadelphia Lüx favorim. Servis çok hızlı.',EN:'Amazing sushi! Philadelphia Lux is my favorite. Very fast service.',DE:'Fantastisches Sushi! Philadelphia Lux ist mein Favorit.',RU:'Отличные суши! Philadelphia Lux — мой фаворит.'},date:'2 weeks ago'},
  {name:'Maria K.',rating:5,text:{TR:'Dragon Mix muhteşemdi. Manzara ve yemek bir arada!',EN:'Dragon Mix was incredible. Great view and food together!',DE:'Dragon Mix war unglaublich. Tolle Aussicht und Essen!',RU:'Dragon Mix был невероятным. Отличный вид и еда!'},date:'1 month ago'},
  {name:'John D.',rating:5,text:{TR:'Antalya\'da en iyi sushi restoranı. Kesinlikle tavsiye ederim.',EN:'Best sushi restaurant in Antalya. Highly recommend!',DE:'Bestes Sushi-Restaurant in Antalya. Sehr empfehlenswert!',RU:'Лучший суши-ресторан в Анталии. Очень рекомендую!'},date:'3 weeks ago'},
  {name:'Elena S.',rating:4,text:{TR:'Çok lezzetli set menüler. Fiyat performans çok iyi.',EN:'Delicious set menus. Great value for money.',DE:'Leckere Set-Menüs. Gutes Preis-Leistungs-Verhältnis.',RU:'Вкусные сет-меню. Отличное соотношение цены и качества.'},date:'1 month ago'},
];
